baseURL = "http://example.org/"
languageCode = "en-us"
title = "Poiste Minecraft Server"
theme = "hugo-ink"
paginate = 5

copyright = ""

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = ""

	# Optional 64x64 avatar image.
	avatar = "https://i.imgur.com/vm77gye.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Kodu"
url = "/"
weight = 1

[[menu.main]]
name = "Kõik Teated"
url = "/posts"
weight = 2


[[menu.main]]
name = "Tägid"
url = "/tags"
weight = 4


[taxonomies]
   tag = "tags"
